title: "Eero Väkiparta"
email: eero@email.eero
description: >- # this means to ignore newlines until "baseurl:"
 I'm awesome !
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: mlhacks
github_username:  EeroVakiparta

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
